# Generated by Django 5.1.5 on 2025-11-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('folio', models.IntegerField(blank=True, null=True)),
                ('tramo', models.IntegerField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('parentescoid', models.IntegerField(blank=True, null=True)),
                ('numpareja', models.IntegerField(blank=True, null=True)),
                ('indigena', models.IntegerField(blank=True, null=True)),
                ('v1', models.IntegerField(blank=True, null=True)),
                ('v2', models.IntegerField(blank=True, null=True)),
                ('v3', models.IntegerField(blank=True, null=True)),
                ('v4', models.IntegerField(blank=True, null=True)),
                ('v5', models.IntegerField(blank=True, null=True)),
                ('v6', models.IntegerField(blank=True, null=True)),
                ('v7', models.IntegerField(blank=True, null=True)),
                ('v8', models.IntegerField(blank=True, null=True)),
                ('v9', models.IntegerField(blank=True, null=True)),
                ('v9_e', models.IntegerField(blank=True, null=True)),
                ('v10', models.IntegerField(blank=True, null=True)),
                ('v10_e', models.IntegerField(blank=True, null=True)),
                ('v11', models.IntegerField(blank=True, null=True)),
                ('v11_e', models.IntegerField(blank=True, null=True)),
                ('e1', models.IntegerField(blank=True, null=True)),
                ('e2', models.IntegerField(blank=True, null=True)),
                ('e3', models.IntegerField(blank=True, null=True)),
                ('e4', models.IntegerField(blank=True, null=True)),
                ('s1a', models.IntegerField(blank=True, null=True)),
                ('s1b', models.IntegerField(blank=True, null=True)),
                ('s1c', models.IntegerField(blank=True, null=True)),
                ('s1d', models.IntegerField(blank=True, null=True)),
                ('s1e', models.IntegerField(blank=True, null=True)),
                ('s1f', models.IntegerField(blank=True, null=True)),
                ('s2a', models.IntegerField(blank=True, null=True)),
                ('s2b', models.IntegerField(blank=True, null=True)),
                ('s2c', models.IntegerField(blank=True, null=True)),
                ('s2d', models.IntegerField(blank=True, null=True)),
                ('s2e', models.IntegerField(blank=True, null=True)),
                ('o1', models.IntegerField(blank=True, null=True)),
                ('o2', models.IntegerField(blank=True, null=True)),
                ('o3', models.IntegerField(blank=True, null=True)),
                ('o4', models.IntegerField(blank=True, null=True)),
                ('o5', models.IntegerField(blank=True, null=True)),
                ('o6', models.IntegerField(blank=True, null=True)),
                ('o7', models.IntegerField(blank=True, null=True)),
                ('o8', models.IntegerField(blank=True, null=True)),
                ('o9', models.IntegerField(blank=True, null=True)),
                ('y1', models.IntegerField(blank=True, null=True)),
                ('y2', models.IntegerField(blank=True, null=True)),
                ('y3', models.IntegerField(blank=True, null=True)),
                ('informante', models.IntegerField(blank=True, null=True)),
                ('fecha_encuesta', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.IntegerField(blank=True, null=True)),
                ('c_zona', models.IntegerField(blank=True, null=True)),
                ('sexo', models.IntegerField(blank=True, null=True)),
                ('fechanacimiento', models.IntegerField(blank=True, null=True)),
                ('nacionalidad_id', models.IntegerField(blank=True, null=True)),
                ('fecha_calificacion', models.IntegerField(blank=True, null=True)),
                ('periodo_rsh', models.CharField(blank=True, max_length=10, null=True)),
                ('c_calle_fps', models.CharField(blank=True, max_length=50, null=True)),
                ('n_calle_uni_rsh', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_ah', models.CharField(blank=True, max_length=10, null=True)),
                ('c_cod_ah_fps', models.IntegerField(blank=True, null=True)),
                ('c_ah_nom', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'datos',
                'managed': False,
            },
        ),
    ]
