# Generated by Django 5.1.5 on 2025-11-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Censo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('annio', models.IntegerField()),
            ],
            options={
                'db_table': 'censo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CensoUv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('total_pers', models.IntegerField(blank=True, null=True)),
                ('densidad', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('total_vivi', models.IntegerField(blank=True, null=True)),
                ('hombres', models.IntegerField(blank=True, null=True)),
                ('mujeres', models.IntegerField(blank=True, null=True)),
                ('edad_0a5', models.IntegerField(blank=True, null=True)),
                ('edad_6a14', models.IntegerField(blank=True, null=True)),
                ('edad_15a64', models.IntegerField(blank=True, null=True)),
                ('edad_64ymas', models.IntegerField(blank=True, null=True)),
                ('iam', models.IntegerField(blank=True, null=True)),
                ('idd', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'censo_uv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Omz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'omz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microservicio', models.CharField(max_length=100)),
                ('email_usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('parametros', models.TextField()),
            ],
            options={
                'db_table': 'registro_consulta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uv',
            fields=[
                ('cod_uv', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'uv',
                'managed': False,
            },
        ),
    ]
