# Generated by Django 6.0.4 on 2026-04-25 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='censo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='censouv',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='omz',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='registroconsulta',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='sb',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='uv',
            options={'managed': True},
        ),
    ]
